Add template to the widgets
sumocoders/fork-partners pull request #11
Opened 2017-02-15 13:27 UTC by bjorvack

Make it possible to have different templates for each widget

2017-02-15 13:32 UTC, carakas commented on src/Backend/Modules/Partners/Domain/Widget/WidgetType.php
> +        $theme = Model::get('fork.settings')->get('Core', 'theme', 'core');
in principle you should inject fork.settings via the constructor and create a service of the form but I'm willing to let this one slip

2017-02-15 13:33 UTC, carakas approved these changes

2017-02-15 14:38 UTC, carakas requested changes

2017-02-15 14:38 UTC, carakas commented on src/Backend/Modules/Partners/Actions/Edit.php
> +        $form = $this->createForm(new WidgetType($theme), $editWidget);
dit is deprecated en mag dus niet meer, als je het zo wilt doen omdat je met fork settings niet makkelijk als service kan werken moet je het doorgeven als form option

2017-02-16 07:46 UTC, bjorvack commented on src/Backend/Modules/Partners/Actions/Edit.php
> +        $form = $this->createForm(new WidgetType($theme), $editWidget);
fixed 3429477

2017-02-16 08:03 UTC, carakas requested changes

2017-02-16 08:03 UTC, carakas commented on src/Backend/Modules/Partners/Actions/Edit.php
> +
why did you add an enter here?

2017-02-16 08:05 UTC, bjorvack commented on src/Backend/Modules/Partners/Actions/Edit.php
> +
fixed 	76a5736

2017-02-16 08:05 UTC, carakas approved these changes

2017-02-16 08:08 UTC, bjorvack commented
@StijnVrolijk nog remarks?

2017-02-16 08:30 UTC, merged