Convert module to be Fork 5.
sumocoders/fork-partners pull request #12
Opened 2017-08-10 13:16 UTC by ohvitorino

The module is currently not compatible with Fork 5. This PR makes the necessary changes to make it compatible.

2017-08-10 13:29 UTC, jonasdekeukelaere requested changes

2017-08-10 13:29 UTC, jonasdekeukelaere commented on src/Backend/Modules/Partners/Actions/Delete.php
> +            );
Best hier nog een `return;` zetten achter de redirect.

2017-08-10 13:29 UTC, jonasdekeukelaere commented on src/Backend/Modules/Partners/Actions/Edit.php
> +            $this->redirect(Model::createURLForAction('Index', null, null, ['error' => 'non-existing']));
same

2017-08-11 09:16 UTC, ohvitorino commented on src/Backend/Modules/Partners/Actions/Delete.php
> +            );
Fixed 1a10186f

2017-08-11 09:16 UTC, ohvitorino commented on src/Backend/Modules/Partners/Actions/Edit.php
> +            $this->redirect(Model::createURLForAction('Index', null, null, ['error' => 'non-existing']));
Fixed 1a10186f

2017-08-11 11:51 UTC, StijnVrolijk approved these changes

2017-08-11 11:52 UTC, jonasdekeukelaere approved these changes

2017-08-17 13:34 UTC, merged